<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0-windows</TargetFrameworks>
		<UseWindowsForms>true</UseWindowsForms>
		<IsPackable>False</IsPackable>
		<IsTestProject>True</IsTestProject>
		<IsPublishable>False</IsPublishable>
		<GenerateAssemblyInfo>False</GenerateAssemblyInfo>
		<CopyCodeCoverageMetadata>False</CopyCodeCoverageMetadata>
		<Parallelize>true</Parallelize>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="TestMunger.cs" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="MSTest.TestFramework" />
		<PackageReference Include="MSTest.TestAdapter" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net48'">
		<Reference Include="System.Data" />
		<Reference Include="System.Drawing" />
		<Reference Include="System.Design" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\ObjectListView\ObjectListView.csproj" />
	</ItemGroup>
</Project>